config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'

  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations', confirmations: 'confirmations' }

  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
	end

  resources :users do

  	resource :profile
  	resources :employments do
      resources :leave_requests do
        resource :rejection_message
      end
      get 'leave_request_by_hr' => 'leave_requests#leave_request_by_hr'
      resources :add_leaves, only: [:new, :create]
    end
  end

  resources :companies do
    resources :leave_types
    resources :holidays
    resources :departments
    resources :costs
    resources :reports, only: [:index] do
      collection do
        get :remaining_leaves
      end
    end
    resources :projects do
      get 'enter_time', on: :collection
      post 'entered_time', on: :collection
      get 'reports', on: :collection
      post 'create_client', on: :collection
    end
    resources :time_requests do
      get 'excel_export', on: :collection
    end
    resources :project_times, only: [:update, :create]
    get 'employees' => 'companies#employees_index'
    get 'leave_requests' => 'companies#leave_requests_index'
    resources :invites
  get 'import_page' => 'companies#import_page'
    get 'employee_import_page' => 'companies#employee_import_page'
    post :import_employees
    post :delete_employees
    post :import_leave_requests
    post :delete_leave_requests
  end

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications/notification_index' => 'notifications#notification_index'
  get 'notifications/read_all', to: 'notifications#read_all'


  namespace :dashboard do
    resources :contact_messages
    resources :endorsements
    resources :features
    resources :owners
    resources :plans
    resources :roles
    resources :testimonials
    resources :site_settings
    resources :landing_page_settings
    resources :user_home_page_settings
    resources :plans
    root to: "site_settings#index"
    devise_for :admins, skip: :registrations
  end

  get 'search' => 'pages#search'
  get 'team' => 'pages#team'
	get 'about' => 'pages#about'
	root 'pages#home'
end

app/models/employment.rb
class Employment < ApplicationRecord
	belongs_to :company
	belongs_to :user, required: false

	has_many :leave_requests
	has_many :leave_amounts, through: :leave_requests
	has_many :leave_reductions
	has_many :notifications, dependent: :destroy
	has_many :add_leaves

	has_many :projects, through: :onboardings
	has_many :onboardings
	has_many :project_times, through: :onboardings
	has_many :departments, through: :projects
	has_many :costs

	# Add Manager
	has_many :subordinates, class_name: 'Employment',
	                        foreign_key: :manager_id
	belongs_to :manager, class_name: 'Employment', optional: true

	# Email Invitation
	has_many :invitations, :class_name => "Invite", :foreign_key => 'recipient_id'
  has_many :sent_invites, :class_name => "Invite", :foreign_key => 'sender_id'

	accepts_nested_attributes_for :leave_reductions

	validates :start_date,
				:user_id,
				:role_id,
				presence: true


	# validates :salary, presence: true, numericality: {greater_than: 0 }

	after_commit :new_employment_same_company, on: :update
	after_commit :hr_before, on: :create

	ransack_alias :employee_name, :user_profile_first_name_or_user_profile_last_name


	def regularized?
		regularized == true
	end

	def new_employment_same_company(acceptance: nil)
		if self.acceptance == true
			same_employment = Employment.where(user_id: self.user_id).where(company_id: self.company_id)
			same_employment_count = same_employment.count
			if same_employment_count > 1
			no_end_dates = same_employment.where(end_date: nil)
			no_end_dates
				.where.not(id: self.id)
				.update_all(end_date: Time.zone.today)
			end
		end
	end

	def hr_before
		@hr_officer = Role.find(1)
		if self.user.employments
			.where(role_id: @hr_officer.id)
			.where(company_id: self.company_id)
			.present? &&
			self.role_id != @hr_officer.id
		self.update(role_id: @hr_officer.id)
		end
	end

	def current_employment(user_given, company_given)
		Employment.find_by(user_id: user_given.id, company_id: company_given.id)
	end

	def manager_names
		if user.nil?
			"NO USER"
		else
			"#{user.profile.first_name} #{user.profile.last_name}"
		end
	end

	def employment_names
		if user.nil?
			"NO USER"
		else
			"#{user.profile.first_name} #{user.profile.last_name}"
		end
	end

	def full_name
		if user.nil?
			"NO USER"
		else
			"#{user.profile.first_name} #{user.profile.last_name}"
		end
	end

	def is_hr?
		@hr_officer = Role.find(1)
		self.blank? ? false : self.role_id == @hr_officer.id
	end

	def is_employee?
		@employee = Role.find(2)
		self.blank? ? false : self.role_id == @employee.id
	end

	def is_manager?
		@manager = Role.find(3)
		self.blank? ? false : self.role_id == @manager.id
	end
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
	before_action :authenticate_user!
  # before_action :only_current_user
  before_action :set_user_and_employment, only: [:edit, :update]

  def new
		if @current_companies.present?
			@available_companies = Company.where('id != ?', @current_companies.ids) || Company.all
		else
			@available_companies = Company.all
		end
		@user = User.find(params[:user_id])
  	@employment = @user.employments.build
  end

  def create
    @user = User.find(params[:user_id])
  	@employment = @user.employments.build(employment_params)
  	if @employment.save
			create_notification_join_accepted(@employment)
	    flash[:success] = "Employment Created!"
	    redirect_to user_path( params[:user_id] )
	  else
	  	# flash[:failure] = "Error in Update!"
	    render action: :new
	  end
  end

	def edit
		@managers = @current_employment.company.employments.where.not(role_id: @employee.id)
		@current_role_id = @current_employment.role_id
		@employment.company.leave_types.each do |leave_type|
			@employment.leave_reductions.build(leave_type_id: leave_type.id)
		end
	end

	def update
		if params[:make_hr]
			@employment.update(role_id: @hr_officer.id)
		elsif params[:make_non_hr]
			@employment.update(role_id: @employee.id)
		elsif params[:regularize]
			@employment.update(regularized: true)
		elsif params[:make_non_regular]
			@employment.update(regularized: false)
		elsif params[:make_manager]
			@employment.update(role_id: @manager.id)
		elsif params[:make_employee]
			@employment.update(role_id: @employee.id)
		end
		if @employment.update_attributes(employment_params)
	    flash[:success] = "Employment Updated!"
      redirect_to edit_user_employment_url(@employment.user_id, @employment.id)
  	else
	  	# flash[:failure] = "Error in Update!"
	    render action: :edit
	  end
	end

  def show
		@current_employment = @current_user.employments.where( company_id: @employment.company_id, acceptance: true).first
  end

	def leave_request_by_hr
		@current_employment = @current_user.employments.where( company_id: @employment.company_id, acceptance: true).first
	end

  private

  def set_user_and_employment
  	@user = User.find(params[:user_id])
  	@employments = @user.employments
    @employment = @user.employments.find_by_id( params[:id] )
    @current_employment = @current_user.employments.where( company_id: @employment.company_id, acceptance: true).first
  end

  def employment_params
  	params.require(:employment).permit(
            :id,
            :start_date,
            :end_date,
            :salary,
            :acceptance,
            :acceptor_id,
            :company_id,
            :user_id,
            :role_id,
						:regularized,
						:manager_id,
						leave_reductions_attributes: [
							:amount,
							:date,
							:leave_type_id,
							:employment_id
							]
						)
  end

	def create_notification_join_company(employment)
		@hr_officers = employment.company.employments.where(role_id: 1)
		Array.wrap(@hr_officers).each do |hr_officer|
			Notification.create(
				user_id: hr_officer.user.id,
				acting_user_id: @current_user.id,
				employment_id: employment.id,
				leave_request_id: nil,
				notice_type: 'join_company',
				read: false)
		end
	end

  # def only_current_user
  #   @user = User.find( params[:user_id] )
  #   redirect_to(root_url) unless @user == current_user
  # end

end

app/views/employments/_Subordinate_options.html.erb
<% if method == :patch && @current_employment.is_manager? && @employment.manager_id != @current_employment.id %>
  <div class="columns">
    <%= form_for @employment, url: url, method: method do |t| %>
      <%= t.hidden_field :manager_id, value: @current_employment.id %>
      <%= t.submit 'Make Subordinate', class: "button warning margin-none add-button-border" %>
    <% end %>
  </div>
<% end %>
<% if method == :patch && @current_employment.is_manager? && @employment.manager_id == @current_employment.id %>
  <div class="columns">
    <%= form_for @employment, url: url, method: method do |t| %>
      <%= t.hidden_field :manager_id, value: nil %>
      <%= t.submit 'Remove Subordinate', class: "button warning margin-none add-button-border" %>
    <% end %>
  </div>
<% end %>

app/views/employments/_Subordination_options.html.erb
<% if @current_employment.is_manager? && @employment.manager_id != @current_employment.id && @current_user != @user %>
  <div class="columns">
    <%= form_for @employment, url: url, method: method do |t| %>
      <%= t.hidden_field :manager_id, value: @current_employment.id %>
      <%= t.submit 'Make Subordinate', class: "button warning margin-none add-button-border" %>
    <% end %>
  </div>
<% end %>
<% if @current_employment.is_manager? && @employment.manager_id == @current_employment.id && @current_user != @user %>
  <div class="columns">
    <%= form_for @employment, url: url, method: method do |t| %>
      <%= t.hidden_field :manager_id, value: nil %>
      <%= t.submit 'Remove Subordinate', class: "button warning margin-none add-button-border" %>
    <% end %>
  </div>
<% end %>

app/views/employments/_add_leave_button.html.erb
<div class="columns">
  <%= link_to "Add Leaves", new_user_employment_add_leafe_url(@employment.user, @employment), class: 'button button-primary add-button-border horizontal-max' %>
</div>

app/views/employments/_company_employment.html.erb
<% unless :join_request == true %>
	<% if employment.acceptance.present? %>
		<% @current_employment =  @current_employments.find_by(company_id: employment.company_id, acceptance: true) %>
		<tr class="table-data">
			<td><%= link_to "#{employment.user.profile.first_name} #{employment.user.profile.last_name}", user_url(employment.user_id, company: @company.id) %></td>
      <td><%= better_date(employment.start_date) %></td>
			<td><%= better_date(employment.end_date) %></td>
			<td class='text-center'>
				<% if employment.regularized == true %>
					<div class="callout small no-margin no-padding success">
						Regular
					</div>
				<% else %>
					<div class="callout small no-margin no-padding alert">
						Non-regular
					</div>
				<% end %>
			</td>

  		<%# content_tag(:td, number_with_delimiter(employment.salary)) if hr? && employed_here? %>
			<td class='text-center'><%= Role.find(employment.role_id).name %></td>
			<td class='text-center'>
				<% if employment.manager.nil? %>
				<% else %>
				<%= employment.manager.user.profile.first_name %>
					<%= employment.manager.user.profile.last_name %>
				<% end %>
			</td>
			<%= content_tag(:td, render('employments/employment_button', employment: employment, location: 'company_employment'), class: "edit-column") if @current_employment.present? && (@current_employment.is_hr? || @current_employment.is_manager?)  %>
		</tr>
	<% end %>
<% end %>

app/views/employments/_company_join_request.html.erb
<tr class="table-data">
  <td><%= link_to "#{employment.user.profile.first_name} #{employment.user.profile.last_name}", user_url(employment.user_id, company: @company.id) %></td>
  <td><%= better_date(employment.start_date) %></td>
  <%# content_tag(:td, number_with_delimiter(employment.salary)) if hr? && employed_here? %>
  <td><%= Role.find(employment.role_id).name %></td>
  <% if (@current_employments.find_by(company_id: params[:id]).present?) &&
    (@current_employment.role_id == @hr_officer.id) && (employment.acceptance.nil?) %>
    <td>
      <%= form_for employment, url: user_employment_url(employment.user, employment), method: :patch, in_company: true do |f| %>
        <%= f.hidden_field :acceptance, value: true %>
        <%= f.hidden_field :acceptor_id, value: @current_user.id %>
        <%= f.submit "Accept", class: "button small expanded success"%>
      <% end %>
    </td>
    <td>
      <%= form_for employment, url: user_employment_url(employment.user, employment), method: :patch, in_company: true do |f| %>
        <%= f.hidden_field :acceptance, value: false %>
        <%= f.hidden_field :acceptor_id, value: @current_user.id %>
        <%= f.submit "Reject", class: "button small expanded alert" %>
      <% end %>
    </td>
  <% else %>
    <td colspan="1"></td>
    <td colspan="1"></td>
  <% end %>
</tr>

app/views/employments/_employment.html.erb
	<tr class="table-data">
		<td><%= link_to employment.company.name, company_url(employment.company_id) %></td>
		<td><%= better_date(employment.start_date) %></td>
		<td><%= better_date(employment.end_date) %></td>

		<!-- <td> -->
			<%# if @user.employments.find_by(company_id: employment.company_id).present? %>
				<%# if (@current_employment.present? && @current_employment.is_hr?) || (@user == @current_user) %>
					<%# number_with_delimiter(employment.salary) %>
				<%# end %>
			<%# end %>
		<!-- </td> -->

		<td>
			<%= employment.acceptance.nil? ? "Waiting" : (employment.acceptance == true ? "Approved" : "Rejected") %>
		</td>
		<td class='text-center'><%= Role.find(employment.role_id).name %></td>
		<td class='text-center'>
			<% if employment.manager.nil? %>
			<% else %>
			<%= employment.manager.user.profile.first_name %>
				<%= employment.manager.user.profile.last_name %>
			<% end %>
		</td>
		<%= content_tag(:td, render('employments/employment_button', employment: employment, location: 'company_employment'), class: "edit-column") if @current_employment.present? && (@current_employment.is_hr? || @current_employment.is_manager?) %>
	</tr>

app/views/employments/_employment_button.html.erb
<% if employment.acceptance.nil? %>
<% else %>
  <% if (@current_employment.present?) || @current_user == employment.user %>

    <div class="button secondary small no-margin reflow" data-toggle="employee-dropdown-<%= employment.id %>-<%= location %>"><i class="fa fa-bars white-text"></i></div>
    <section class="dropdown-pane no-padding reflow" id="employee-dropdown-<%= employment.id %>-<%= location %>" data-dropdown data-hover="true" data-hover-pane="true" >
      <div class="row horizontal-max no-margin no-padding collapse">
        <div class="columns small-up-1 medium-up-1">
          <div class="columns no-padding">
            <%= link_to 'Edit Employment', edit_user_employment_url(employment.user_id, employment), class: "button white-c horizontal-max no-margin text-left"  %>
          </div>
          <% if @current_employment.is_hr? || (@current_employment.id == employment.manager_id) %>
            <div class="columns no-padding">
              <%= link_to "Create Leave Request for Employee",
                  user_employment_leave_request_by_hr_url(employment.user_id, employment),
                  class: "button white-c horizontal-max no-margin text-left" %>
            </div>
          <% end %>
        </div>
      </div>
    </section>
    </div>

  <% end %>
<% end %>

app/views/employments/_employments_form.html.erb
<div class="row">
  <div class="small-12 medium-offset-3 medium-6">

			<%= form_for @employment, url: url, method: method  do |f| %>

			<%= show_error_message(@employment) %>

		  	<div class="m-well align-middle">
          <div class="space"></div>
          <% if method == :post %>
  					<div class="field">
  					<%= f.label :company_id, "Company" %>
  					<%= f.collection_select(:company_id, @available_companies, :id, :name, {prompt: true}, {class: "select-select horizontal-max"}) %>
  						<div class="small-font-size">
  							If you can't find your company. You can create one.
  						</div>
  					</div>
  					<div class="space"></div>
          <% end %>

  					<div class="field">
  						<%= f.label :start_date, "Start Date" %>
  						<%= f.text_field :start_date, class: "datepickerstart", value: nil, "data-value": better_date2(@employment.start_date) %>
  					</div>

					<% unless @employment.id.nil? %>
						<% if (@current_employment.role_id == @hr_officer.id) && (@current_employment.company_id == @employment.company_id)%>
							<div class="field">
								<%= f.label :end_date, "End Date" %>
								<%= f.text_field :end_date, class: "datepickerstart", value: nil, "data-value": better_date2(@employment.end_date) %>
                <p class="small-font-size">* Enter if the user has left the company</p>
							</div>
						<% end %>
					<% end %>

          <% if hr? || manager? %>
  					<div class="field">
  						<%# f.label :salary %>
  						<%# f.text_field :salary %>
  					</div>
          <% end %>

					<div class="space"></div>

          <% unless @employment.id.nil? || method == :post || @current_employment.is_employee? %>
            <% if @current_employment.is_hr? %>

              <div class="field">
                <%= f.label :manager_id %>
                <%= f.collection_select(:manager_id, @managers, :id, :manager_names, {prompt: true}, {class: "select-select horizontal-max"}) %>
                <div class="space2"></div>
              </div>
            <% end %>
            <div class="row medium-up-2 small-up-1">
              <%= render 'hr_officer_options_new', url: url, method: method, f: f %>
              <%= render 'regularization_options', url: url, method: method, f: f %>
              <%= render 'manager_options_new', url: url, method: method, f: f %>
              <%# render 'subordination_options_new', url: url, method: method %>

              <%= render 'add_leave_button' if hr? %>
            </div>
            <div class="space2"></div>
					<% else%>
						<%= f.hidden_field :role_id, value: @employee.id %>
					<% end %>
            <%# render 'leave_reduction_form', f: f %>
					<%= f.submit 'Update', class: "button primary" %>
				</div>
		<% end %>
	</div>
</div>

app/views/employments/_leave_reduction_form.html.erb
<% if @current_employment.present? && @current_employment.is_hr? %>
  <h4>Leave Reductions</h4>
    <%= f.fields_for :leave_reductions do |leave_r| %>
      <%= leave_r.hidden_field :leave_type_id %>
      <h4><%= leave_r.object.leave_type.name %></h4>
      <div class="field">
        <%= leave_r.label :date, 'Leave Reduction Date' %>
        <%= leave_r.text_field :date, class: 'datepickerstart'%>
      </div>
      <div class="field">
        <%= leave_r.label :amount, 'Leave Reduction Amount' %>
        <%= leave_r.text_field :amount %>
        <p class="small-font-size">* Reduces amount of leaves of the user due to leave usage before Tseklis use.</p>
      </div>
    <% end %>
  <% end %>

app/views/employments/_manager_options_new.html.erb
<% if(@current_employment.is_hr?) && (@employment.is_employee? || @employment.is_hr?) %>
  <div class="columns">
    <%= f.submit 'Make Manager', name: 'make_manager', class: "button warning margin-none add-button-border" %>
  </div>
<% end %>

app/views/employments/_regularization_options.html.erb
<% if @current_employment.is_hr? && @employment.regularized == false %>
  <div class="columns">
    <%= f.submit 'Regularize', name: 'regularize', class: "button success add-button-border " %>
  </div>
<% end %>
<% if @current_employment.is_hr? && @employment.regularized == true %>
  <div class="columns">
    <%= f.submit 'Make Non-Regular', name: 'make_non_regular', class: "button alert add-button-border" %>
  </div>
<% end %>

app/views/employments/_subordination_options_new.html.erb
<% if @current_employment.is_manager? && @employment.manager_id != @current_employment.id && @current_user != @user %>
  <div class="columns">
    <%= form_for @employment, url: url, method: method do |t| %>
      <%= t.hidden_field :manager_id, value: @current_employment.id %>
      <%= t.submit 'Make Subordinate', class: "button warning margin-none add-button-border" %>
    <% end %>
  </div>
<% end %>
<% if @current_employment.is_manager? && @employment.manager_id == @current_employment.id && @current_user != @user %>
  <div class="columns">
    <%= form_for @employment, url: url, method: method do |t| %>
      <%= t.hidden_field :manager_id, value: nil %>
      <%= t.submit 'Remove Subordinate', class: "button warning margin-none add-button-border" %>
    <% end %>
  </div>
<% end %>

app/views/employments/edit.html.erb
<div class="small-nav white-border-bottom">
	<div class="row small-nav">
		<div class="columns">
			<%= link_to 'Back', url_for(:back), class:  'small-nav-link' %> 	&nbsp; 	&nbsp; | 	&nbsp; &nbsp;  <%= link_to "Home", root_url, class: 'small-nav-link' %> &nbsp; > &nbsp; <%= link_to @employment.company.name, company_url(@employment.company_id), class: 'small-nav-link' %>  &nbsp; > &nbsp; Employment Edit
		</div>
	</div>
</div>

<div class="form-header">
  <div class="row text-center align-middle form-header">

    <div class="columns">
      <h4><%= @user.profile.first_name %> <%= @user.profile.last_name %></h4>
      <h2>Employment Edit</h2>
    </div>

  </div>

  <div class="row">
    <div class="columns">
      <%= render 'employments_form', url: user_employment_path(@user, @employment), method: :patch %>
    </div>
  </div>
</div>

app/views/employments/new.html.erb
<div class="form-header">
  <div class="row text-center align-middle form-header">

    <div class="columns">

      <h2>New Employment</h2>

    </div>
  </div>

  <div class="row">
    <div class="columns">
      <%= render 'employments_form', url: user_employments_path(current_user), method: :post %>
    </div>
  </div>
</div>