config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'

  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations', confirmations: 'confirmations' }

  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
	end

  resources :users do

  	resource :profile
  	resources :employments do
      resources :leave_requests do
        resource :rejection_message
      end
      get 'leave_request_by_hr' => 'leave_requests#leave_request_by_hr'
      resources :add_leaves, only: [:new, :create]
    end
  end

  resources :companies do
    resources :leave_types
    resources :holidays
    resources :departments
    resources :costs
    resources :reports, only: [:index] do
      collection do
        get :remaining_leaves
      end
    end
    resources :projects do
      get 'enter_time', on: :collection
      post 'entered_time', on: :collection
      get 'reports', on: :collection
      post 'create_client', on: :collection
    end
    resources :time_requests do
      get 'excel_export', on: :collection
    end
    resources :project_times, only: [:update, :create]
    get 'employees' => 'companies#employees_index'
    get 'leave_requests' => 'companies#leave_requests_index'
    resources :invites
  get 'import_page' => 'companies#import_page'
    get 'employee_import_page' => 'companies#employee_import_page'
    post :import_employees
    post :delete_employees
    post :import_leave_requests
    post :delete_leave_requests
  end

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications/notification_index' => 'notifications#notification_index'
  get 'notifications/read_all', to: 'notifications#read_all'


  namespace :dashboard do
    resources :contact_messages
    resources :endorsements
    resources :features
    resources :owners
    resources :plans
    resources :roles
    resources :testimonials
    resources :site_settings
    resources :landing_page_settings
    resources :user_home_page_settings
    resources :plans
    root to: "site_settings#index"
    devise_for :admins, skip: :registrations
  end

  get 'search' => 'pages#search'
  get 'team' => 'pages#team'
	get 'about' => 'pages#about'
	root 'pages#home'
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

	has_many :employments
	has_many :users, through: :employments
	has_many :leave_requests, through: :employments
	has_many :leave_amounts, through: :leave_requests
	has_many :holidays
	has_many :departments
	has_many :projects, through: :departments
	has_many :project_times, through: :projects
	has_many :clients, through: :projects
	has_many :onboardings, through: :projects
	has_one	 :address
	has_many :user_import_passwords, through: :users

	has_one  :company_leave_setting
	has_many :leave_types, dependent: :destroy

	has_many :invites

	accepts_nested_attributes_for :employments,
		:address,
		:leave_types,
		:company_leave_setting,
		:holidays,
		:departments,
		allow_destroy: true


	validates :name, presence: true, uniqueness: true

	attr_accessor :segmented_monthly_leaves

	def self.search(search)
	  if search
	    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
	  else
	  end
	end

	def segmented_leaves(date_used)
		leave = []
		self.leave_types.each do |p|
		 	value = self.leave_amounts
		 		.where(date: date_used)
		 		.where(leave_request_id: self.leave_requests.ids)
		 		.where("leave_requests.acceptance = true")
		 		.where("leave_requests.leave_type_id = ?", p.id)
		 		.sum(:amount)
		 	name = p.name
			leave << {name => value}
		end
		return leave
	end

	def total_leaves(date_used)
		self.leave_amounts.where(date: date_used).sum(:amount)
	end

	def number_of_users
		self.users.size
	end

	def offshore?
		if name == "The Offshore Concept Consulting, Inc."
			offshore = true
		else
			offshore = false
		end
		return offshore
	end

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

	before_action :restrict_index, only: [:index]
	before_action :set_up, only: [ :edit, :update, :show ]
	after_action :destroy_leave_type_blank, only: [:update ]
	before_action :redirect_not_company, only: [ :edit, :update, :show, :leave_requests_index]

  helper ApplicationHelper

	def index
		@companies = Company.all
	end

	def new
		@user = User.find(current_user.id)
		@company = Company.new
		@employment = @company.employments.build
		@address = @company.build_address
		@company_leave_setting = @company.build_company_leave_setting
		@leave_types = @company.leave_types.build
	end

	def create
		@user = User.find(current_user.id)
		@company = Company.new(company_params)
		if @company.save
			flash[:success] = "Company Created"
			redirect_to root_path
		else
			render action: :new
		end
	end

	def edit
		1.times do
			leave_type = @leave_types.build
		end
			holiday = Company.find(params[:id]).holidays.build
	end

	def update
		if @company.update_attributes(company_params)
	    flash[:success] = "Company Updated!"
	    redirect_to edit_company_url( params[:id] )
	  else
	  	# flash[:failure] = "Error in Update!"
	    render action: :edit
	  end
	end

	def show
		@per_show = 10
		@user = current_user
		@sum = 0
		@leaves = []
		@month_segmented_leaves = @company.segmented_leaves(Time.zone.today.all_month)
		@month_total_leaves = @company.total_leaves(Time.zone.today.all_month)
		@current_employment = Employment.where(user_id: @user, company_id: @company, acceptance: true).first

		# Search
		# @search_employee = User.where('employments.company_id = ?', @company.id).ransack(params[:q])
		# @result_employees = @search_employee.result(distinct: true).includes(:profile, :employments)

		@q_employments = Employment.where(company_id: @company.id).where(acceptance: true).reverse_order.ransack(params[:q_employments])
		@employments = @q_employments.result(distinct: true).page(params[:employments_page]).per(@per_show)

		@year_search = params[:leave_data_year].to_s.to_i
		@year_search = Time.zone.today.strftime('%Y').to_i if @year_search == 0

		# Kaminari
    @leave_requests = @company.leave_requests.reverse_order
		@leave_requests_excel = @leave_requests
    @leave_requests = Kaminari.paginate_array(@leave_requests).page(params[:leave_requests_page]).per(@per_show)

		# @employments = @company.employments.where('employments.acceptance = true').reverse_order
		# @employments = Kaminari.paginate_array(@employments).page(params[:employments_page]).per(@per_show)
    @has_leave_types = @company.leave_types.present? ? true : false
		@join_requests = @company.employments.where('employments.acceptance IS null').reverse_order
		@join_requests = Kaminari.paginate_array(@join_requests).page(params[:join_requests_page]).per(@per_show)

		# leave_data
		if params[:month_used].nil?
			@leave_data = @company.employments.includes(:leave_amounts)
				.where('leave_amounts.date between ? and ?', Time.zone.today.at_beginning_of_month, Time.zone.today.at_end_of_month)
				.where('leave_requests.acceptance = ?', true)
				.references(:leave_amounts)
		elsif params[:month_used].to_s.to_i == 0
			@leave_data = @company.employments.includes(:leave_amounts)
				.where('leave_amounts.date between ? and ?', Date.new(@year_search).at_beginning_of_year, Date.new(@year_search).at_end_of_year)
				.where('leave_requests.acceptance = ?', true)
				.references(:leave_amounts)
		else
			@leave_data = @company.employments.includes(:leave_amounts)
				.where('leave_amounts.date between ? and ?', Date.new(@year_search, params[:month_used].to_s.to_i).at_beginning_of_month, Date.new(@year_search, params[:month_used].to_s.to_i).at_end_of_month)
				.where('leave_requests.acceptance = ?', true)
				.references(:leave_amounts)
		end



		@months = [{Year: 0}, {January: 1}, {February: 2}, {March: 3}, {April: 4}, {May: 5}, {June: 6}, {July: 7}, {August: 8}, {September: 9}, {October: 10}, {November: 11 }, {December: 12 }]

		# manager subordinates
		if user_signed_in? && @current_employment.present?
			@subordinates = @current_employment.subordinates
				.where(end_date: nil, acceptance: true)
			@subordinate_leave_requests = LeaveRequest.where(employment_id: @subordinates.ids).reverse_order
			@subordinate_leave_requests = Kaminari.paginate_array(@subordinate_leave_requests).page(params[:lr_page_manager_dashboard]).per(@per_show)
		end


		respond_to do |format|
	    format.html # index.html.erb
	    format.js # ajax will call this format not html or json
	    # format.json { render json: @portefeuillemodeles }
		end

 	end

	def month_change
		@date = @date
	end

	def employees_index
		@company = Company.find(params[:company_id])
		@employments = @company.employments
			.joins(user: :profile)
			.order('profiles.last_name')
			# .where(end_date: nil)
	end

	def leave_requests_index
		@company = Company.find(params[:company_id])
		@current_employment = @company.employments.where(user_id: @current_user, acceptance: true).last
		@leave_requests = @company.leave_requests.reverse_order
    @leave_requests = Kaminari.paginate_array(@leave_requests).page(params[:leave_requests_page]).per(50)
		respond_to do |format|
			format.html
			format.xlsx
		end

	end

	def import_page
		@company = Company.find(params[:company_id])
	end

	def employee_import_page
		@company = Company.find(params[:company_id])
		respond_to do |format|
			format.html
			format.xlsx
			format.csv
		end
	end

	def import_leave_requests
		@company = Company.find(params[:company_id])
		LeaveRequest.import(params[:file], @company, @current_user)
		flash[:success] = "Leave Requests Imported"
		redirect_to company_import_page_url(@company)
	end

	def import_employees
		time1 = Time.zone.now
		@company = Company.find(params[:company_id])
		User.import(params[:file], @company, @current_user)
		time2 = Time.zone.now
		duration = time2 - time1
		flash[:success] = "Employees Imported. #{duration} seconds."
		redirect_to company_employee_import_page_url(@company)
	end

	def delete_leave_requests
		@company = Company.find(params[:company_id])
		LeaveRequest.mass_delete(params[:file], @company, @current_user)
		flash[:success] = "Deleted submitted Leave Request data."
		redirect_to company_import_page_url(@company)
	end

	def delete_employees
		@company = Company.find(params[:company_id])
		User.mass_delete(params[:file], @company, @current_user)
		flash[:success] = "Deleted submitted Employee data."
		redirect_to company_employee_import_page_url(@company)
	end

	private

		def company_params
		  params.require(:company).permit(
				:id,
				:name,
		  	employments_attributes: [
		  		:id,
	  			:start_date,
	  			:end_date,
	  			:salary,
	  			:acceptance,
	  			:acceptor_id,
	  			:user_id,
	  			:company_id,
	  			:role_id,
					:regularized
	  		],
		  	address_attributes: [
		  		:id,
		  		:first_line,
		  		:second_line,
		  		:city_town,
		  		:province,
		  		:country,
		  		:zip_code,
		  		:company_id
		  	],
			  leave_types_attributes: [
			  	:id,
		  		:name,
		  		:company_id,
		  		:amount,
		  		:_destroy
		  	],
			  company_leave_setting_attributes: [
	        :id,
	        :company_id,
		  		:leave_month_expiration,
		  		:leave_month_start,
		  		:prorate_accrual,
		  		:include_weekends
		  	],
		  	holidays_attributes: [
		  		:id,
		  		:name,
		  		:date,
		  		:company_id
		  	],
				departments_attributes: [
					:id,
					:name
				]
		  )
	end


	def set_up
		@company = Company.find_by_id(params[:id])
		@employments = @company.employments
		@address = @company.address
		@leave_types = @company.leave_types
		@leave_requests = @company.leave_requests
		@company_leave_setting = @company.company_leave_setting
	end

	def destroy_leave_type_blank
		leave_types = @leave_types
		leave_types.each do |leave_types_array|
			leave_type = leave_types_array
			LeaveType.destroy(leave_type.id) if leave_type[:id].nil? || (leave_type[:amount].nil? || leave_type[:name].blank?)
		end
	end

	def leave_data
		return @company.employments.includes(:leave_amounts)
			.where('leave_amounts.date between ? and ?', Time.zone.today.at_beginning_of_month, Time.zone.today.at_end_of_month)
			.where('leave_requests.acceptance = ?', true)
			.references(:leave_amounts)
	end

	def redirect_not_company
		@company = Company.find(params[:company_id]) if params[:action] == 'leave_requests_index'
    unless user_signed_in? && current_user.employments.where(company: @company).present?
      redirect_to root_url
    end
  end

	def restrict_index
		authenticate_or_request_with_http_basic('Administration') do |username, password|
		 ActiveSupport::SecurityUtils.secure_compare(username, "admin") &&
		 ActiveSupport::SecurityUtils.secure_compare(password, "!tseklisadministratorpass")
	 end
	end

end

app/views/companies/_company.html.erb
<div class="columns small-12 medium-5">
	<div class="company_card callout white-c">
		<div class="row">
			<div class="columns">
				<div class="space"></div>
			<h3><%= link_to company.name, company_url(company.id) %></h3>
			<div  class="small-font-size">
				<% unless company.address.nil? %>
					<%= company.address.first_line %>,
					<%= company.address.second_line %>
					<%= company.address.city_town %>,
					<%= company.address.province %>,
					<%= company.address.country %>
					<%= company.address.zip_code %>
				<% end %>
			</div>
		<div class="space"></div>
			</div>
		</div>
		<div class="space"></div>
		<div class="row align-middle ">
			<div class="columns medium-5">
				<div class="text-right">
					<i class="fa fa-calendar-o fa-2x"></i>
				</div>
			</div>
			<div class="columns medium-6 text-center card-row white-bg">
				<%= company.created_at.strftime("%B %d, %Y") %>
			</div>
		</div>
		<div class="row align-middle ">
			<div class="columns medium-5">
				<div class="text-right">
					<i class="fa fa-users fa-2x"></i>
				</div>
			</div>
			<div class="columns medium-6 text-center card-row white-bg">
				<%= company.number_of_users %>
			</div>
		</div>
		<div class="row align-middle ">
			<div class="columns medium-5">
				<div class="text-right">
					<i class="fa fa-suitcase fa-2x"></i>
				</div>
			</div>
			<div class="columns medium-6 text-center card-row white-bg">
				<%= company.leave_amounts.sum(:amount) %> leaves
			</div>
		</div>
	</div>
</div>

app/views/companies/_company_leave_requests_table.html.erb
<% if @company.leave_requests.present? %>
	<div class="row vertical-padding">
		<div class="columns">
			<div class="row align-center">
				<div class="columns">
					<h4><%= link_to "Leave Requests", company_leave_requests_url(@company)%></h4>
				</div>
				<div class="columns text-right">
					<%= link_to "Export as .xlsx", company_leave_requests_url(@company, format: 'xlsx'), class: 'button button-primary add-button-border' %>
				</div>
			</div>

			<div class="space"></div>
			<div class="row">
				<div class="column">
					<div class="table-scroll">
						<table class="table" style='min-width: 100%;'>
							<thead>
								<tr>
									<th>Employee</th>
									<th>Title</th>
									<th>Leave Type</th>
									<th>Start</th>
									<th>End</th>
									<th class='text-center'>Status</th>
									<th class='text-center'>Reviewer</th>
									<th class="text-center">Amount</th>
									<th colspan="1"></th>
									<th colspan="1"></th>
								</tr>
							</thead>
							<tbody id="leave_requests">
	              <%= render @leave_requests, at_company: true %>
							</tbody>
						</table>
					</div>
          <div class="row align-center text-center">
            <div class="column shrink">
							<div id="leave_request_paginator_company">
								<%= paginate @leave_requests, param_name: 'leave_requests_page', remote: true %>
							</div>
							<div class="small-font-size" id="leave_request_info">
								<%= page_entries_info @leave_requests %>
							</div>
						</div>
          </div>
				</div>
		</div>
	</div>

<% end %>

app/views/companies/_company_leave_settings_fields.html.erb
<%= input.fields_for :company_leave_setting, @company_leave_setting do |company_leave_settings| %>

	<h5>Company Leave Settings</h5> <br />

  <div class="field">
	  <%= company_leave_settings.label :leave_month_expiration %>
	  <%= company_leave_settings.number_field :leave_month_expiration, placeholder: "Leaves expire after a specified # of Months" %>

   </div>

  <div class="field">
	  <%= company_leave_settings.label :leave_month_start %>
	  <%= company_leave_settings.number_field :leave_month_start, placeholder: "# of Months after the Employee's start date" %>
  </div>

  <div class="field">
	  <%= company_leave_settings.check_box :include_weekends %>
	  <%= company_leave_settings.label :include_weekends %>
  </div>

	<div class="field">
	  <%= company_leave_settings.check_box :regularized_employees_only %>
	  <%= company_leave_settings.label :regularized_employees_only, 'Allow leaves to Regularized Employees only' %>
  </div>

  <!-- <div class="field">
	  <%= company_leave_settings.check_box :prorate_accrual %>
	  <%= company_leave_settings.label :prorate_accrual %>
	  <p class="small-font-size">This will calculate the amount of leaves to give to the Employee on a daily basis starting from the accrual start month. The number of available leaves is rounded to the nearest 0.25.</p>
  </div> -->

  <div class="space"></div>
<% end -%>

app/views/companies/_company_leaves_taken.erb
<% if @company.leave_requests.where(acceptance: true).present? %>
	<div class="show-leave" id='company-leaves-taken'>
		<div class="row vertical-padding">
			<div class="columns">
				<% if @company.leave_requests.present? %>
					<h2><%= Time.zone.today.strftime("%B %Y") %> <small>Company leaves</small></h2>
					<div class="row align-middle vertical-padding2">
						<div class="columns small-12 medium-12 text-center">
							<div class="row align-middle">
								<div class="columns medium-3 text-center">
									<h1 class="h-1">
										<%= @month_total_leaves %>
									</h1>
									<h5>
										Total Used
									</h5>
								</div>
								<div class="columns">
									<div class="row small-up-1 medium-up-3">
										<% @month_segmented_leaves.each do |p| %>
											<% p.each do |k,v| %>
												<div class="columns text-center">
													<h1><%= v %></h1>
													<p><%= k %></p>
												</div>
											<% end %>
										<% end %>
									</div>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/companies/_leave_type_fields.html.erb
<h5>Leave Types</h5> <br />

<%= input.nested_fields_for :leave_types do |leave_type| %>

	<% unless leave_type.object.name ==
		"Unpaid" || leave_type.object.name ==
			"Non-paid" %>
		<div class="row">
			<div class="columns" style="padding-right: 0.25rem;">
			 	<%= leave_type.label :name %>
		  	<%= leave_type.text_field :name,  placeholder: "Enter Leave Type" %>
			</div>
			<div class="columns" style="padding-left:0.25rem;">
			  <%= leave_type.label :amount, "Annual Leaves" %>
		  	<%= leave_type.number_field :amount, placeholder: "Annual Leaves" %>
			</div>
		</div>

		<div class="row">
			<div class="columns">
			  <%# leave_type.remove_nested_fields_link 'Delete', class: "small-font-size"%>
		  	<%= leave_type.check_box :_destroy %>
		  	<%= leave_type.label :_destroy, "Remove", class: "small-font-size" %>
			</div>
		</div>

	  <div class="space"></div>
	<% end %>
<% end %>

<div class="space"></div>
<div class="row">
	<div class="columns text-center">
		<%= input.add_nested_fields_link :leave_types, "Add a leave Type", class: "button warning"%>
	</div>

</div>

app/views/companies/_leaves.html.erb
<div class="row">
	<div class="columns medium-offset-2 medium-8">
		<div class="row">
			<div class="columns text-center">
				<h1>
					<%# @leaves2.each do |p| %>
						<%# p.each do |k,v| %>
							<%# @sum += v %>		
						<%# end %> 
					<%# end %>							
					<%# @sum %>
				</h1>
				<p>
					Total Leaves
				</p>
			</div>
		</div>
		<div class="row ">
			<% @leaves.each do |p| %>
				<% p.each do |k,v| %>
					<div class="columns text-center">
							<h1><%= v %></h1>
							<p><%= k %></p>	 
					</div>
				<% end %> 
			<% end %>	
		</div>	
	</div>
</div>


<div class="space2"></div>

app/views/companies/_manager_dashboard.html.erb
<div id="manager-dashboard" class='hide'>
  <div class="section-blue-small no-padding">
    <div class="table-scroll">
      <div class="row section-blue-small no-padding no-margin horizontal-max">
        <div class="columns">
          <div class="row medium-up-2">
            <div class="columns section-blue-small-padding">
              <h4>Team Members</h4>
              <% if @current_employment.subordinates.empty? %>
                <div class="text-center">
                  <h3>No Data</h3>
                </div>
              <% else %>
                <table class="table"  style='min-width: 100%;'>
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Start Date</th>
                      <th class='text-center'>Regularization</th>
                      <th colspan="1"></th>
                    </tr>
                  </thead>
                  <tbody id="manager_subordinates">
                    <%= render partial: 'companies/manager_subordinates', collection: @subordinates, as: 'employment' %>
                  </tbody>
                </table>
              <% end %>
            </div>
            <div class="columns section-yellow-small-padding">
              <h4 class='white-text'>Leave Requests</h4>
              <% if @current_employment.subordinates.empty? %>
                <div class='text-center'>
                  <h3>No Data</h3>
                </div>
              <% else %>
                <div class="column">
        					<table class="table"  style='min-width: 100%;'>
        						<thead>
        							<tr>
        								<th>Employee</th>
        								<th>Title</th>
        								<th>Leave Type</th>
        								<th class='text-center'>Status</th>
        								<th class="text-center">Amount</th>
        							</tr>
        						</thead>
        						<tbody id="lr_manager_dashboard">
                      <%= render partial: "companies/subordinate_leave_requests", collection: @subordinate_leave_requests, at_company: true, as: "leave_request" %>
        						</tbody>
        					</table>
                  <div class="row align-center text-center">
                    <div class="column shrink">
        							<div id="lr_paginator_manager_dashboard">
        								<%= paginate @subordinate_leave_requests, param_name: 'lr_page_manager_dashboard', remote: true %>
        							</div>
        							<div class="small-font-size" id="leave_request_info_manager_dashboard">
        								<%= page_entries_info @subordinate_leave_requests %>
        							</div>
        						</div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/_remaining_leaves_row.html.erb
<tr class="black-text">
  <td>
    <%= resource.full_name %>
  </td>
  <% @sum = 0 %>
  <% @company.leave_types.each do |u| %>
    <% if u.name == "Unpaid" %>
    <% else %>
      <td>
        <% to_add = resource.available_leaves(@company, u)[:amount] %>
        <%= bignum(to_add) %>
        <% @sum += to_add %>
      </td>
    <% end %>
  <% end %>
  <td>
    <%= bignum(@sum) %>
  </td>
</tr>

app/views/companies/_subordinate_leave_requests.html.erb
<tr class="table-data">
  <td>
    <%= link_to user_url(leave_request.employment.user) do %>
      <%= leave_request.employment.user.profile.first_name%>
      <%= leave_request.employment.user.profile.last_name %>
    <% end %>
  </td>
  <td>
    <%= link_to leave_request.title, user_employment_leave_request_url(leave_request.employment.user, leave_request.employment, leave_request) %>
  </td>
  <td>
    <%= LeaveType.find(leave_request.leave_type_id).name %>
  </td>
  <td class='text-center'>
    <% if leave_request.acceptance.nil? %>
      <div class="callout small no-margin no-padding secondary">
        Waiting
      </div>
    <% elsif leave_request.acceptance == true %>
      <div class="callout small no-margin no-padding success">
        Approved
      </div>
    <% else %>
      <div class="callout small no-margin no-padding alert">
        Rejected
      </div>
    <% end %>
  </td>
  <td class="text-center">
    <%= leave_request.show_amount %>
  </td>
</tr>

app/views/companies/employees_index.html.erb
<div class="show-header">
  <div class="row align-middle show-header">
    <div class="columns">
      <h4><%= link_to @company.name, company_url(@company) %></h4>
      <h1>Employees</h1>
    </div>
  </div>
</div>
<div class="space2"></div>
<div class="row">
  <div class="columns">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Salary</th>
          <th>Role</th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody id="employments">
        <%= render partial: 'employments/company_employment', collection: @employments, as: 'employment'%>
      </tbody>
    </table>
  </div>
</div>

app/views/companies/import_page.html.erb
<div class="small-nav white-border-bottom">
	<div class="row small-nav">
		<div class="columns">
			<%= link_to 'Back', url_for(:back), class:  'small-nav-link' %> 	&nbsp; 	&nbsp; | 	&nbsp; &nbsp;  <%= link_to "Home", root_url, class: 'small-nav-link' %> &nbsp; > &nbsp; <%= link_to @company.name, company_url(@company), class: 'small-nav-link' %>  &nbsp; > &nbsp; Import Leave Requests
		</div>
	</div>
</div>
<div class="form-header no-margin">
  <div class="row form-header align-middle">
    <div class="columns small-12 medium-6">
      <h3>Import Leave Requests</h3>
      <h5>CSV / Excel</h5>
    </div>
    <div class="columns small-12 medium-offset-1 medium-4 align-self-middle">
      <div class="m-well">
        <div class="space"></div>
        <%= form_tag company_import_leave_requests_path(@company), multipart: true do %>
          <%= file_field_tag :file %>
          <div class="space"></div>
          <%= submit_tag "Import", class: 'button primary add-button-border'%>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="columns small-12 medium-4">
    <h4>Download Sample Import File</h4>
    <%= link_to 'Download Link', '/leave_request_imports/Tseklis-Sample-Import.xlsx' %>
  </div>
  <div class="columns small-12 medium-4">
    <h4>Delete Import Data</h4>
    <p>Delete Imported Data in one go by uploading the same file here.</p>
    <div class="m-well">
      <div class="space"></div>
      <%= form_tag company_delete_leave_requests_path(@company), multipart: true do %>
        <%= file_field_tag :file %>
        <div class="space"></div>
        <%= submit_tag "Delete", class: 'button primary add-button-border'%>
      <% end %>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="show-header">
  <div class="row align-middle show-header">

    <div class="columns">

      <h1 class="no-margin">Companies</h1>
      <p>All the clients we serve.</p>

    </div>

    <div class="columns small-1 medium-2 ">
      <%= link_to "Create Company", new_company_url, class: "button primary" %>
    </div>
  </div>


  <div class="row small-up-1 medium-up-3 vertical-padding2">
    <% Array.wrap(@companies).each do |company|  %>
    <%= render 'company',
    url: company_url(company),
    company: company
    %>
    <% end %>
  </div>
</div>

<div class="space5"></div>